import React from 'react';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {HeroUIProvider} from "@heroui/react";
import Header from "../../layouts/header";
import PageWrapper from "../../layouts/wrapper";
import Footer from "../../layouts/footer";

/**
 * A Primary Layout for the App.
 * 
 * @param {string} props.children - The text to display inside the button.
 */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeroUIProvider>
          <PageWrapper>
            <Header />
              {children}
        <Footer />
        </PageWrapper>
        </HeroUIProvider>
      </body>
    </html>
  );
}

export default RootLayout